/**
 * @author Anyuru David Derrick
 * 
 * 
 * @param {Number} generatedOTP A six digit random code that has been generated by a random generator.
 * @param {Number} submittedOTP A six digit random generator that has been entered by the user.
 * @returns {Boolean} true if the two parameters match otherwise false
 */

export const verifyOTP = ( submittedOTP, generatedOTP ) => submittedOTP === generatedOTP ? true: false